// halaman ini adalah halaman yang pertama akan di jalankan atau diekseskusi
//halaman ini sama seperti appshell di pakagerouter yang outputannya akan muncul di semua halaman
"use client";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './navbar'
import { useState } from 'react'
import { usePathname } from "next/navigation"

const inter = Inter({ subsets: ['latin'] })

//jadi jika kita ada di login dan register maka navbarnya tidak akan dimunculkan atau di disable
const disableNavbar = ["/login", "/register"];

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state, setState] = useState(0);
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableNavbar.includes(pathname) && <Navbar/>}
        {/* <h1>Contoh Layout {state}</h1>
        <button onClick={() => setState(state + 1)}>Klik</button> */}
        {/* setelah mengeksekusi halaman ini, selanjutnya dia akan mengeksekusi children yang terdapat di dalam halaman yang sedang kita buka */}
        {children}
      </body>
    </html>
  )
}
